name: GranitePublicAffairs
favicon: null
layout_spectrum: 0.0058446922339499
typography_spectrum: 0.8750315101351589
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a1531'
    - '#bcbdc1'
    - '#fefefc'
    - '#2d4d8c'
    - '#568fb5'
  brandStrength: 0.43427717383019626
  lightness: 0.5708245073910803
  saturation: 0.642580394167453
  rhythmicContrast: 0.5
purpose: []
